services:
  postgres:
    image: postgres:15
    container_name: course-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db:
    driver: local
   